#!/bin/bash
# user creation and restriction script
# AT NO POINT SHOULD THE EXECUTION OF THIS SCRIPT BE AFFECTED
# BY A USER, IT SHALL NOT BE KILLED BEFORE IT FINISHES EXECUTION

set -e;

function err() {
    echo "ERROR: $@";
    exit 1;
}

user=$1;
[[ -n "$user" ]] || err "Invalid username";

# create user
useradd "$user";

# change default shell to bash
usermod --shell /bin/bash "$user";

# create user home folder
mkdir "/home/$user";
chown "$user:$user" "/home/$user";
chmod u=rwx,g=,o= "/home/$user";

# copy VITEJ file
sudo -u "$user" cp /opt/avava-hello/VITEJ.md "/home/$user/VITEJ.md"

# set quotas to 15G soft 20G hard, do not restrict
# inode counts
setquota -u "$user" 15G 20G 0 0 -a;

# create authorized_keys file
sudo -u "$user" mkdir -p "/home/$user/.ssh";
sudo -u "$user" touch "/home/$user/.ssh/authorized_keys";
chmod 600 "/home/$user/.ssh/authorized_keys";

# create database user
check_collision() {
    psql -U postgres -lqt | cut -d \| -f 1 | grep -qw $1
}

db_id=`shuf -i 1000-9999 -n 1`;
while check_collision "db$db_id"; do
    db_id=`shuf -i 1000-9999 -n 1`;
done;
db_pass=`pwgen -B -1 15`;
{
    echo "CREATE ROLE "db$db_id" LOGIN PASSWORD '$db_pass';";
    echo "CREATE DATABASE "db$db_id" WITH OWNER "db$db_id";";
    echo "REVOKE ALL ON DATABASE "db$db_id" FROM PUBLIC;";
} | psql -U postgres
# correct public schema owner
psql -U postgres -d "db$db_id" -c "ALTER SCHEMA public OWNER TO \"db$db_id\"";

# Add DB login info to .pgpass and set PGUSER in .profile
touch "/home/$user/.pgpass";
chown "$user:$user" "/home/$user/.pgpass";
chmod 600 "/home/$user/.pgpass";
echo "localhost:*:*:db$db_id:$db_pass" > "/home/$user/.pgpass";
echo -e "# Set default psql user to the one generated by avava-hello\nexport PGUSER=\"db$db_id\"" >> "/home/$user/.profile";
