#!/bin/bash

if [ $EUID -ne 0 ]; then
    echo "Tento skript musi byt spusten jako root (sudo)";
    exit 1;
fi;

DB_FILE=/opt/avava-misc-scripts/avava-mysql-db
USR=${SUDO_USER:-root}

ask_yes() {
    read -r -p "$1 [y/N]" resp
    case "$resp" in
        [yY])
	    ;;
	*)
	    exit 0;
	    ;;
    esac
}

user_exists() {
    mysql -sNe "SELECT user FROM mysql.user WHERE user='$1'" | grep -q "$1"
}

new_db() {
    if ! [[ "$2" =~ ^[a-zA-Z0-9]+$ ]]; then
        echo "$2";
        echo "Popisek musi byt ve tvaru [a-zA-Z0-9]+";
        exit 1;
    fi;
    ask_yes "Prejete si vytvorit novou databazi s popiskem '$2'?";

    password=$(pwgen 20 1);
    db="db$(shuf -i1000-9999 -n1)";
    while user_exists "$db"; do
        db="db$(shuf -i1000-9999 -n1)";
    done;
    echo "creating new db '$db' for $USR" | logger -t avava-mysql
    echo "$USR $db $2" >> $DB_FILE;
    {
        echo "CREATE USER '$db'@'localhost' IDENTIFIED BY '$password';";
        echo "CREATE DATABASE $db;";
        echo "GRANT ALL ON $db.* TO '$db'@'localhost';"
        echo "FLUSH PRIVILEGES;";
    } | mysql -sN
    echo "nazev db a uzivatele: $db";
    echo "heslo: $password";
    echo "poznamenejte si heslo, nikdy se znovu nezobrazi";
}

list_db() {
    echo "uzivatel databaze/db_uzivatel popisek";
    echo "listing db for $1" | logger -t avava-mysql
    if [ "$1" == "root" ]; then
        cat $DB_FILE;
    else
        grep "^$1 " $DB_FILE;
    fi;
}

delete_db() {
    if ! [[ "$2" =~ ^db[0-9]{4}$ ]]; then
        echo "'$2' neni nazev databaze vytvorene timto skriptem";
        exit 1;
    fi;
    if ! list_db $USR | grep -q "$2"; then
        echo "k databazi nemate pristup nebo neexistuje";
    fi;
    sed -i "/^$USR $2/d" $DB_FILE;
    ask_yes "Prejete si smazat databazi '$2'?";
    {
        echo "DROP USER '$2'@'localhost';";
        echo "DROP DATABASE $2;";
        echo "FLUSH PRIVILEGES;";
    } | mysql -sN
}
help() {
    echo "sudo avava-psql help|new|list|delete ...";
    echo "    new <popisek>     vytvori novou databazi s popiskem <popisek>, popisek je jen";
    echo "                      pro zapamatovani, nazev i jmeno uzivatele bude vygenerovano";
    echo "    list              zobrazi vsechny vytvorene databaze";
    echo "    delete <db_name>  smaze databazi <db_name>!!";
    echo "    help              zobrazi tuto zpravu";
}

case $1 in
    new)
        new_db $@
    ;;
    list)
        list_db $USR
    ;;
    delete)
        delete_db $@
    ;;
    *)
        help
    ;;
esac
