#!/bin/bash

SCRIPT_NAME="$(basename "$0")"

case "$SCRIPT_NAME" in
    avava-psql)
        DATABASE_NAME=PostgreSQL
        ;;
    avava-mysql)
        DATABASE_NAME=MySQL
        ;;
    *)
        exit 1
        ;;
esac

if [ $EUID -ne 0 ]; then
    echo "Tento skript musi byt spusten jako root (sudo)";
    exit 1;
fi;

# load db specific functions
source "/opt/avava-misc-scripts/$SCRIPT_NAME-lib"
DB_FILE="/opt/avava-misc-scripts/$SCRIPT_NAME-db"

USR=${SUDO_USER:-root}
SCRIPT=0

ask_yes() {
    if [[ $SCRIPT -eq 1 ]]; then
        return;
    fi;

    read -r -p "$1 [y/N]" resp
    case "$resp" in
        [yY])
        ;;
    *)
        exit 0;
        ;;
    esac
}

new_db() {
    if ! [[ "$2" =~ ^[a-zA-Z0-9.@-]+$ ]]; then
        echo "$2";
        echo "Popisek musi byt ve tvaru [a-zA-Z0-9.@-]+";
        exit 1;
    fi;
    ask_yes "Prejete si vytvorit novou $DATABASE_NAME databazi s popiskem '$2'?";

    password=$(pwgen 20 1);
    db="db$(shuf -i1000-9999 -n1)";
    while db_exists "$db"; do
        db="db$(shuf -i1000-9999 -n1)";
    done;
    echo "creating new db '$db' for $USR" | logger -t "$SCRIPT_NAME";
    echo "$USR $db $2" >> $DB_FILE;
    create_db "$db" "$password"

    if [[ $SCRIPT -eq 0 ]]; then
        echo "nazev db a uzivatele: $db";
        echo "heslo: $password";
        echo "poznamenejte si heslo, nikdy se znovu nezobrazi";
    else
        echo "$db $password";
    fi;
}

list_db() {
    [[ $SCRIPT -eq 0 ]] && echo "uzivatel database/db_user popisek";
    echo "listing db for $1" | logger -t "$SCRIPT_NAME";
    if [ "$1" == "root" ]; then
        cat $DB_FILE;
    else
        grep "^$1 " $DB_FILE || true;  # suppress grep's exit code 1
    fi;
}

delete_db() {
    if ! [[ "$2" =~ ^db[0-9]{4}$ ]]; then
        echo "'$2' neni nazev databaze vytvorene timto skriptem";
        exit 1;
    fi;
    if ! list_db $USR | grep -q "$2"; then
        echo "k databazi nemate pristup nebo neexistuje";
        exit 1;
    fi;
    ask_yes "Prejete si smazat databazi '$2'?";
    echo "deleting db '$2' for $USR" | logger -t "$SCRIPT_NAME";
    sed -i "/^$USR $2/d" $DB_FILE;
    remove_db "$2"
}

help() {
    echo "sudo $SCRIPT_NAME help|new|list|delete ...";
    echo "    new <popisek>     vytvori novou databazi s popiskem <popisek>, popisek je jen";
    echo "                      pro zapamatovani, nazev i jmeno uzivatele bude vygenerovano";
    echo "    list              zobrazi vsechny vytvorene databaze";
    echo "    delete <db_name>  smaze databazi <db_name>!!";
    echo "    help              zobrazi tuto zpravu";
}

while true; do
    case $1 in
        --script)
            SCRIPT=1;
            shift;
        ;;
        new)
            new_db $@;
            break;
        ;;
        list)
            list_db $USR;
            break;
        ;;
        delete)
            delete_db $@;
            break;
        ;;
        *)
            help;
            break;
        ;;
    esac
done
