#!/bin/bash

if [ $EUID -ne 0 ]; then
    echo "Tento skript musi byt spusten jako root (sudo)";
    exit 1;
fi;

DB_FILE=/opt/avava-misc-scripts/avava-psql-db
USR=${SUDO_USER:-root}
SCRIPT=0

ask_yes() {
    if [[ $SCRIPT -eq 1 ]]; then
        return;
    fi;

    read -r -p "$1 [y/N]" resp
    case "$resp" in
        [yY])
        ;;
    *)
        exit 0;
        ;;
    esac
}

user_exists() {
    psql -U postgres -lqt | cut -d \| -f 1 | grep -qw $1
}

new_db() {
    if ! [[ "$2" =~ ^[a-zA-Z0-9]+$ ]]; then
        echo "$2";
        echo "Popisek musi byt ve tvaru [a-zA-Z0-9]+";
        exit 1;
    fi;
    ask_yes "Prejete si vytvorit novou PostgreSQL databazi s popiskem '$2'?";

    password=$(pwgen 20 1);
    db="db$(shuf -i1000-9999 -n1)";
    while user_exists "$db"; do
        db="db$(shuf -i1000-9999 -n1)";
    done;
    echo "creating new db '$db' for $USR" | logger -t avava-psql;
    echo "$USR $db $2" >> $DB_FILE;
    {
        echo "CREATE ROLE "$db" LOGIN PASSWORD '$password';";
        echo "CREATE DATABASE "$db" WITH OWNER "$db";";
        echo "REVOKE ALL ON DATABASE "$db" FROM PUBLIC;";
    } | psql -U postgres
    # correct public schema owner
    psql -U postgres -d "$db" -c "ALTER SCHEMA public OWNER TO \"$db\"";

    if [[ $SCRIPT -eq 0 ]]; then
        echo "nazev db a uzivatele: $db";
        echo "heslo: $password";
        echo "poznamenejte si heslo, nikdy se znovu nezobrazi";
    else
        echo "$db $password";
    fi;
}

list_db() {
    echo "uzivatel database/db_user popisek";
    echo "listing db for $1" | logger -t avava-psql;
    if [ "$1" == "root" ]; then
        cat $DB_FILE;
    else
        grep "^$1 " $DB_FILE || true;  # suppress grep's exit code 1
    fi;
}

delete_db() {
    if ! [[ "$2" =~ ^db[0-9]{4}$ ]]; then
        echo "'$2' neni nazev databaze vytvorene timto skriptem";
        exit 1;
    fi;
    if ! list_db $USR | grep -q "$2"; then
        echo "k databazi nemate pristup nebo neexistuje";
    exit 1;
    fi;
    echo "deleting db '$2' for $USR" | logger -t avava-psql;
    ask_yes "Prejete si smazat databazi '$2'?";
    sed -i "/^$USR $2/d" $DB_FILE;
    {
        echo "DROP DATABASE \"$2\";";
        echo "DROP ROLE \"$2\";";
    } | psql -U postgres;
}
help() {
    echo "sudo avava-psql help|new|list|delete ...";
    echo "    new <popisek>     vytvori novou databazi s popiskem <popisek>, popisek je jen";
    echo "                      pro zapamatovani, nazev i jmeno uzivatele bude vygenerovano";
    echo "    list              zobrazi vsechny vytvorene databaze";
    echo "    delete <db_name>  smaze databazi <db_name>!!";
    echo "    help              zobrazi tuto zpravu";
}

while true; do
    case $1 in
        --script)
            SCRIPT=1;
            shift;
        ;;
        new)
            new_db $@;
            break;
        ;;
        list)
            list_db $USR;
            break;
        ;;
        delete)
            delete_db $@;
            break;
        ;;
        *)
            help;
            break;
        ;;
    esac
done
